@baseUrl = http://localhost:8002

GET {{baseUrl}}/contact
###

GET {{baseUrl}}/contact/67d8acdbef53d54bdc38d39a
###

POST {{baseUrl}}/contact
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}
###

PUT {{baseUrl}}/contact/67d8acdbef53d54bdc38d39a
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.updated@example.com",
  "favoriteColor": "Green",
  "birthday": "1990-01-01"
}
###

DELETE {{baseUrl}}/contact/67d8acdbef53d54bdc38d39a
###